name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.0.0
      - run: npm install
      - run: next build && next export
      - run: next export
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGES_DEPLOYMENT }}
          publish_dir: ./out
          cname: tmotswagole.github.io
